[package]
name = "y_project_structure"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Using External Packages
rand = "0.8.5"
# a_basic = { version = "0.1.0", path = "../a_basic" }